"""add_gemini_api_key_table

Revision ID: 0f76863d66f1
Revises: 9fab03b2c0e1
Create Date: 2025-06-04 15:38:12.189716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0f76863d66f1'
down_revision = '9fab03b2c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_api_keys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemini_api_keys')
    # ### end Alembic commands ###
