"""add_object_and_field_models

Revision ID: 9fab03b2c0e1
Revises: 86b858019013
Create Date: 2024-06-01 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fab03b2c0e1'
down_revision = '86b858019013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('connection_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('object_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['connection_id'], ['bigquery_configs.id'], name=op.f('fk_objects_connection_id_bigquery_configs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_objects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objects')),
    sa.UniqueConstraint('user_id', 'connection_id', 'object_name', name=op.f('uq_objects_user_id_connection_id_object_name'))
    )
    op.create_table('fields',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('object_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('fk_fields_object_id_objects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    op.drop_table('objects')
    # ### end Alembic commands ###
